### ISSUE TITLE
Needed  to Add new images and videos to merge in the code

### ISSUE THREAD

**Issue by SricharanReddy29** [SricharanReddy29/VERDANT-x-BARREN#8]
Add new images which are related to nature, nature pollution, space.

**Comment by RohanMukka** [comment]
I will do that work bro...

**Comment by Kamal-Poshala** [comment]
please assign me this work

**Comment by Pavan-hitman** [comment]
please assign work for me

**Comment by SricharanReddy29** [comment]
#All of you do the assigned work
